# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
stylua = "johnnymorganz/stylua@0.15.1"
rojo = "rojo-rbx/rojo@7.4.0"
wally = "upliftgames/wally@0.3.2"
selene = "kampfkarren/selene@0.21.1"
# rojo = "rojo-rbx/rojo@6.2.0"